package covenant

import (
	"context"
	"testing"

	"arkade-poker/go/internal/merkel"
	"arkade-poker/go/internal/shuffle"
)

// Complete crypto -> covenant -> hand proof integration. Every token below is
// generated by the production shuffle package for a freshly shuffled deck and
// checked by both its verifier and the actual PSBT/emulator execution harness.
func TestGeneratedShuffleAndRevealsThroughRealEmulator(t *testing.T) {
	ctx := context.Background()
	binding := []byte("go/shuffle-covenant-integration/v1")
	p, err := shuffle.New()
	if err != nil {
		t.Fatal(err)
	}
	var secrets [2]*shuffle.SecretKey
	var keys [2]shuffle.PublicKey
	var verified [2]shuffle.VerifiedPublicKey
	for i := range keys {
		var proof shuffle.OwnershipProof
		secrets[i], keys[i], proof, err = shuffle.GenerateKey(ctx, nil, binding)
		if err != nil {
			t.Fatal(err)
		}
		defer secrets[i].Destroy()
		verified[i], err = shuffle.VerifyOwnership(keys[i], proof, binding)
		if err != nil {
			t.Fatal(err)
		}
	}
	aggregate, err := shuffle.AggregateKeys(verified[:])
	if err != nil {
		t.Fatal(err)
	}
	initial, proof, err := p.ShuffleInitial(ctx, nil, aggregate, binding)
	if err != nil {
		t.Fatal(err)
	}
	first, err := p.VerifyInitial(ctx, aggregate, initial, proof, binding)
	if err != nil {
		t.Fatal(err)
	}
	next, proof, err := p.Shuffle(ctx, nil, aggregate, first, binding)
	if err != nil {
		t.Fatal(err)
	}
	last, err := p.Verify(ctx, aggregate, first, next, proof, binding)
	if err != nil {
		t.Fatal(err)
	}
	var cards [9]shuffle.MaskedCard
	for i := range cards {
		cards[i], err = last.Card(i)
		if err != nil {
			t.Fatal(err)
		}
	}
	h := newTestHand(t, nil)
	params := h.c.params
	params.Players.Player1.EncryptionKey = keys[0]
	params.Players.Player2.EncryptionKey = keys[1]
	params.EncryptedDeal = DealtCards[shuffle.MaskedCard]{HoleCards: PerPlayer[[2]shuffle.MaskedCard]{[2]shuffle.MaskedCard{cards[0], cards[1]}, [2]shuffle.MaskedCard{cards[2], cards[3]}}, Flop: [3]shuffle.MaskedCard{cards[4], cards[5], cards[6]}, Turn: cards[7], River: cards[8]}
	h.c, err = Derive(params, h.c.checkpointScript)
	if err != nil {
		t.Fatal(err)
	}
	var verifiedShares [18]shuffle.VerifiedRevealToken
	h.revealCard = func(actor Player, slot byte, card shuffle.MaskedCard) CardReveal {
		t.Helper()
		b, err := shuffle.RevealBinding([32]byte(h.c.id), slot)
		if err != nil {
			t.Fatal(err)
		}
		token, proof, err := shuffle.Reveal(ctx, nil, secrets[int(actor)-1], card, b)
		if err != nil {
			t.Fatal(err)
		}
		verifiedShares[slot], err = shuffle.VerifyReveal(verified[int(actor)-1], card, token, proof, b)
		if err != nil {
			t.Fatal(err)
		}
		return CardReveal{Share: token, Proof: proof}
	}
	h.start(0)
	h.bet(BettingAction{Kind: Check})
	for street := Flop; street <= River; street++ {
		h.board()
		h.bet(BettingAction{Kind: Check})
		h.bet(BettingAction{Kind: Check})
	}
	h.ownHoles()
	slots := [9][2]int{{0, 14}, {1, 15}, {2, 16}, {3, 17}, {4, 7}, {5, 8}, {6, 9}, {10, 11}, {12, 13}}
	var plain [9]byte
	for i, pair := range slots {
		token, err := shuffle.AggregateReveals([]shuffle.VerifiedRevealToken{verifiedShares[pair[0]], verifiedShares[pair[1]]})
		if err != nil {
			t.Fatal(err)
		}
		plain[i], err = p.RevealCard(cards[i], token)
		if err != nil {
			t.Fatal(err)
		}
	}
	evaluation, err := merkel.Evaluate(ctx, plain)
	if err != nil {
		t.Fatal(err)
	}
	witness := ShowdownWitness{Cards: DealtCards[byte]{HoleCards: PerPlayer[[2]byte]{[2]byte{plain[0], plain[1]}, [2]byte{plain[2], plain[3]}}, Flop: [3]byte{plain[4], plain[5], plain[6]}, Turn: plain[7], River: plain[8]}, RankProofs: PerPlayer[merkel.HandProof]{evaluation.Player1, evaluation.Player2}}
	total := h.tx.TxOut[0].Value
	h.accept(h.c.Showdown(h.tx, Player1, witness))
	if h.tx.TxOut[0].Value+h.tx.TxOut[1].Value != total {
		t.Fatal("payout conservation")
	}
}
